In [1]:
#importing necessary libraries
from __future__ import absolute_import, division, print_function

import tensorflow as tf
from tensorflow import keras

import os
import pandas as pd
import numpy as np
from numpy import *

import matplotlib.pyplot as plt

import pickle

In [2]:
#Loading 2018-2019 stats
nba_18_19 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\18-19-nba_player_stats.pkl")

#adding column name season
nba_18_19.insert(1, 'season', '2018-2019', allow_duplicates = True)
nba_18_19.head()

,player,season,gp,min,pts,fgm,fga,3pm,3pa,ftm,fta,reb,ast,stl,blk,tov
0,James Harden,2018-2019,55.0,37.4,36.5,10.8,24.4,44.2,5.0,13.5,37.1,9.9,11.4,87.1,1.0,5.7
1,Paul George,2018-2019,57.0,36.6,28.9,9.6,21.1,45.5,3.9,9.6,40.5,5.9,7.0,84.0,1.4,6.6
2,Stephen Curry,2018-2019,47.0,34.3,28.8,9.6,19.7,48.9,5.2,11.6,45.0,4.3,4.7,92.2,0.7,4.5
3,Anthony Davis,2018-2019,46.0,35.6,27.8,9.9,19.5,50.8,0.9,2.8,31.8,7.1,8.8,80.5,3.2,9.6
4,Kevin Durant,2018-2019,58.0,35.4,27.6,9.7,18.9,51.6,1.8,5.0,36.4,6.3,7.1,89.5,0.5,6.5

In [3]:
#Loading 2017-2018 stats
nba_17_18 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\17-18-nba_player_stats.pkl")

#adding column name season
nba_17_18.insert(1, 'season', '2017-2018', allow_duplicates = True)

In [4]:
#Loading 2016-2017 stats
nba_16_17 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\16-17-nba_player_stats.pkl")

#adding column name season
nba_16_17.insert(1, 'season', '2016-2017', allow_duplicates = True)

In [5]:
#Loading 2015-2016 stats
nba_15_16 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\15-16-nba_player_stats.pkl")

#adding column name season
nba_15_16.insert(1, 'season', '2015-2016', allow_duplicates = True)

In [6]:
#Loading 2014-2015 stats
nba_14_15 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\14-15-nba_player_stats.pkl")

#adding column name season
nba_14_15.insert(1, 'season', '2014-2015', allow_duplicates = True)

In [7]:
#Loading 2013-2014 stats
nba_13_14 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\13-14-nba_player_stats.pkl")

#adding column name season
nba_13_14.insert(1, 'season', '2013-2014', allow_duplicates = True)

In [8]:
#Loading 2012-2013 stats
nba_12_13 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\12-13-nba_player_stats.pkl")

#adding column name season
nba_12_13.insert(1, 'season', '2012-2013', allow_duplicates = True)

In [9]:
#Loading 2011-2012 stats
nba_11_12 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\11-12-nba_player_stats.pkl")

#adding column name season
nba_11_12.insert(1, 'season', '2011-2012', allow_duplicates = True)

In [10]:
#Loading 2010-2011 stats
nba_10_11 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\10-11-nba_player_stats.pkl")

#adding column name season
nba_10_11.insert(1, 'season', '2010-2011', allow_duplicates = True)

In [11]:
#Loading 2009-2010 stats
nba_09_10 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\09-10-nba_player_stats.pkl")

#adding column name season
nba_09_10.insert(1, 'season', '2009-2010', allow_duplicates = True)

In [12]:
#Loading 2008-2009 stats
nba_08_09 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\08-09-nba_player_stats.pkl")

#adding column name season
nba_08_09.insert(1, 'season', '2008-2009', allow_duplicates = True)

In [13]:
#Loading 2007-2008 stats
nba_07_08 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\07-08-nba_player_stats.pkl")

#adding column name season
nba_07_08.insert(1, 'season', '2007-2008', allow_duplicates = True)

In [14]:
#Loading 2006-2007 stats
nba_06_07 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\06-07-nba_player_stats.pkl")

#adding column name season
nba_06_07.insert(1, 'season', '2006-2007', allow_duplicates = True)

In [15]:
#Loading 2005-2006 stats
nba_05_06 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\05-06-nba_player_stats.pkl")

#adding column name season
nba_05_06.insert(1, 'season', '2005-2006', allow_duplicates = True)

In [16]:
#Loading 2004-2005 stats
nba_04_05 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\04-05-nba_player_stats.pkl")

#adding column name season
nba_04_05.insert(1, 'season', '2004-2005', allow_duplicates = True)

In [17]:
#Loading 2003-2004 stats
nba_03_04 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\03-04-nba_player_stats.pkl")

#adding column name season
nba_03_04.insert(1, 'season', '2003-2004', allow_duplicates = True)

In [18]:
#Loading 2002-2003 stats
nba_02_03 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\02-03-nba_player_stats.pkl")

#adding column name season
nba_02_03.insert(1, 'season', '2002-2003', allow_duplicates = True)

In [19]:
#Loading 2001-2002 stats
nba_01_02 = pd.read_pickle(r"C:\Users\zhika\NBA_ML_PROJECT\nba_stats\01-02-nba_player_stats.pkl")

#adding column name season
nba_01_02.insert(1, 'season', '2001-2002', allow_duplicates = True)

In [20]:
#Combining the dataframes together
combined_data = nba_18_19.append(nba_17_18, ignore_index=True)

#Iterate over the array to append all of the dataframes to combined_data
years_array = [nba_16_17, nba_15_16,nba_14_15,nba_13_14,nba_12_13,nba_11_12,nba_10_11,nba_09_10,nba_08_09,
               nba_07_08,nba_06_07,nba_05_06,nba_04_05,nba_03_04,nba_02_03,nba_01_02]

for year in years_array:
    combined_data = combined_data.append(year, ignore_index=True)

combined_data.head()

,player,season,gp,min,pts,fgm,fga,3pm,3pa,ftm,fta,reb,ast,stl,blk,tov
0,James Harden,2018-2019,55.0,37.4,36.5,10.8,24.4,44.2,5.0,13.5,37.1,9.9,11.4,87.1,1.0,5.7
1,Paul George,2018-2019,57.0,36.6,28.9,9.6,21.1,45.5,3.9,9.6,40.5,5.9,7.0,84.0,1.4,6.6
2,Stephen Curry,2018-2019,47.0,34.3,28.8,9.6,19.7,48.9,5.2,11.6,45.0,4.3,4.7,92.2,0.7,4.5
3,Anthony Davis,2018-2019,46.0,35.6,27.8,9.9,19.5,50.8,0.9,2.8,31.8,7.1,8.8,80.5,3.2,9.6
4,Kevin Durant,2018-2019,58.0,35.4,27.6,9.7,18.9,51.6,1.8,5.0,36.4,6.3,7.1,89.5,0.5,6.5

In [40]:
#Make a dataframe of nba players who are playing this year
nbaplayers_in_2018 = combined_data[combined_data['season'] == '2018-2019']

In [41]:
#Get a list of all active nba players
current_players= nbaplayers_in_2018["player"].tolist()

In [46]:
#Make a new dataframe only active nba players and all the stats from seasons they have played
active_players = combined_data.loc[combined_data['player'].isin(current_players)]
active_players.head()

,player,season,gp,min,pts,fgm,fga,3pm,3pa,ftm,fta,reb,ast,stl,blk,tov
0,James Harden,2018-2019,55.0,37.4,36.5,10.8,24.4,44.2,5.0,13.5,37.1,9.9,11.4,87.1,1.0,5.7
1,Paul George,2018-2019,57.0,36.6,28.9,9.6,21.1,45.5,3.9,9.6,40.5,5.9,7.0,84.0,1.4,6.6
2,Stephen Curry,2018-2019,47.0,34.3,28.8,9.6,19.7,48.9,5.2,11.6,45.0,4.3,4.7,92.2,0.7,4.5
3,Anthony Davis,2018-2019,46.0,35.6,27.8,9.9,19.5,50.8,0.9,2.8,31.8,7.1,8.8,80.5,3.2,9.6
4,Kevin Durant,2018-2019,58.0,35.4,27.6,9.7,18.9,51.6,1.8,5.0,36.4,6.3,7.1,89.5,0.5,6.5